import numpy as np
import pandas as pd
import Bio
from Bio.Seq import Seq


dna10_1 = Seq("CGCCGAAATCCCAGGATGTGACTCAACTGTCTCGTTTTCGCAAAATACAGGCTCTCACTG\
              AGTGTCCAGAGATCCGTTCATTGATTACTCGGACGTTGAGAATATACTCCCCTCACTTGT\
              AAGCTACTGTTAAACTGGATCCGTGCCTGAGTCACCAGGCACCGATATAACCCGCGAGGT\
              GTGATTAGCCCATGATTCGGCACCGAGCAGAGCGAATACCGACGATCTACGTTATTAATC\
              GTTACTCGTGAGAGCTTAGGTTATAAGGAGGACGTACCGAGGCGCTCGCAATTCGAGACC\
              CCCGTAATAGGATACAATAGGAGCTTTGCGGGGGTAGCGCTGTAGCGCCAAACGCGCTCG\
              TTATAGGCGCTGACAATAGACGCGATAGTTGCCCAGACCTAAACAGGTGAGGCTGATCTG\
              AGGTTCAATTCCCCATTTCTCCCTATAGCAACTAAGTGAATCCGCACCAACGTCGCTGAA\
              GGAATGAACTCCTAAGCGCGTACCAGTCTGTCATGTGGTATGCTGTACATTTGTGCTTAT\
              GACTCTTTCTAACTCAGCCACAACCTAAAACGACGCTTATCTTATGCGACCATCATTGCT\
              CCAATTCGCCTGGCCCACTAGGCTGTTCAGACTCGAGTTATAAGTAATGAGCTCTCTCGA\
              CAAGGGAGAGTTCATATGAGTCCCAGAGAAACTTTGGGCAACGAACCGCCACACAGAACG\
              AGTCGTGTCCCAGGCATTCAGTCCGGGCCGCGTTTTAGTGCTGGACTGCGGAGGAGAATC\
              TGTAGGCCCGTTCATGGATAACTGATTCGGCATTAAGACCCTGGATCAACCCACTTACAT\
              CATAGTTATACGATCGTGTATGAACCCTCCTTAGATACCATTTATCCCAGCGTCGTCGGT\
              GTGCACAACAGGGACCAGTACCGGAGAGATCCATTTTTTTTTCCCACATGTGTGAAGCAT\
              GCCC\
              ")
dna10_2 = Seq("CTCTAATGTACTTGATAAAGACTAACCAGAACAGAGGTACCTTAATATTTACTTAGCTGC\
              AGAACAGCATTACCATCCAGTAATCTGTCTCCGGGCAGGATAGGCGTGAGGAAGACTCTG\
              AAGCCAGTTACTTCACCGGAGACGTAGATATAACTCTAAGTGGAATTCGCGAATTATACT\
              GTCCTATGGTCAGTTATGGGCATGCGACTAAACTAGCTACAGCACCTGTTCCAGAAAAGC\
              TAGACTCGACGGCTATGCGCGGTTTAACCGACGAAGAAGTCGGTACAAATCCGCTAAGAC\
              CTCTGTTTGTTCAACAGGCGCGATGACTTAACAGCCCACAAGCCACAGGTGACTCGTATA\
              ATAACAGGTCCCTGCTCTCCATAAGATTGCGACCTATTGTATTTATGAGCCTGAGACGCA\
              CCCACCAACTGACCGTGTCCAGCGGGCTAACTCGAGTTATCGCAAAGCGCTTGGACAGAA\
              CGGATGAAGCCCACGAGATACCATAAAATCGCGCTTCGTTGACGCGCCAGGGCAGGGGCT\
              GGATCGAACGCCGGTCGGGTCTAAGATAAAGCGTGTCTGACTTAGACGCCGAAGGTGAGA\
              CTACGTTATTCCCTCAACCGTTATGTTCTGGTTCCCTCGGGTCCGAAAAGATAGTGGAAG\
              CTGAGGGAGCTTAACATAGGCCTACTAATATTAACAATAAAGGACTCCTATTAATCGGTC\
              TGGAATAGGATACACATTTAATCCCTGTTGTTGCGCGGCTACTCTCAGATTGTGTTGCGT\
              GGGAATGGCTTGACAGTAGCGGGCATCAGCGGGAGTCGAGGTTCTCATGTGCTTTCGGCT\
              ACTGGACCCTTTGTCCAAATATGCCTTCTCATTACGTTGTCAACGTTGCCCTGGAGGCGG\
              GTACTATGGAGTAAGGCGCGTCACGTGGATCGGCGGGAACTGAGCCCTTCCCACGACTCG\
              GAGT")
dna10_3 = Seq("ACGTGCGATATAATAGCGTACAGTATATGCGCGAAGTGACAAACCGCAACATCACTAGAT\
              ACGCCGGGTGACTTGCTCGAGATTGATTTCCACGCATTCAGTTTGACGTAATTGCAGATT\
              GAGCGAAGATACGTACCATGGCCACCGGTGTCGATCATACAAACCACAGTGATTCGTTGC\
              GCTTCTTTTTTGTCGCCCAGTGGTAGCCCTAGCCCCGACTCGGGTGGCTGCTTAACTACT\
              TCTTTAATCCAAACGCATGCTATCAGCCTGTCTTCCTAAGGGAGCCAGTCCATAATATTT\
              CCGACCAAGGAGAACATGGGAAGTTGGCCATCTGTACATGGCAGACTTAAGTCTGATGTT\
              TGATTAGGAAAAATAGTTCCTTTGTCTTAACAGCTCAGAATAGCTTACTCTTCGGGCCGT\
              GTGGAAGCAATGCACGTTGCTTCCCCTCACCGCGATTGAATCAAGCCGCAATCCCGCGCT\
              CCCCCAGGAGCATGAGACCCCGGCTGCTTGTCGTACCGAGGTGCCAACCTATCGCGGAAT\
              AAAACGATGGCCCCCCAAGATCGACCGTTGCACACCGGATGTATATAGACGGGGACGGTT\
              CACAGAGGGCCTAGGTTAGCGCGAATCGAGCGCTAAAGCCCGGCGGGCTGTAGAGTCCGA\
              AGCCAACGTGCCGCGACCGTCTGATTCCGGGTTCTTATGGGCGCATGACTTTAGTGGAGC\
              TAAGCAGCTAATCACGTACTGTACGAGAACGTCTGAGGACACGTCGGGTTCGCTACCTTG\
              GCCATGGTTTTCATCACTGTTGTTTGGATGCCGAATTGCCATAGTATTAAATGCGACCAG\
              TTGTTTAATGTCGGCGGCCTAGTATTCAGGCTGCCACGGGCTCAGAACAAAGGGTAAGTA\
              GGTGATAGGTAGACGCTACTTAAGATGCGGCGAATTACGCAAGTGGTGGTATAAGGCAAG\
              AGCT")
dna10_4 = Seq("GAGTATATGAACGTCGATGGATCGCAAAGTCCCGCTAAGCACCTGTAATTGTACTAGAAA\
              GTGACAGATCGAGAACCATTCGACCGCATGCGCAAACCAGAGAATAGTGTGTAAGGTCGT\
              GCAATTCTCTGGGACATAGACTGTGAACCGGCAGCCTGTTGGCCCAGCTACTTGGTCTCA\
              TCGCTGGTAATCGGCAAACAAACTAGTGTCATCATACCTCCTTGCCAACCGTACAACGGC\
              GTTGCTGGAGTTGATATGTTGGTGGCTGCCAAATGTTCATGCCCGAGCTATCGACTTGTA\
              TAAAGGGCTTGGTTCGTGTTGCCATGACGCGCAGGCAAGCATAATAGACTCGCTATATCT\
              ATTGTGGGTCGTCGAATTAGCTTTTTTGATATGACTGACTACGTTACTTAGAACGAGAAG\
              CAACCAGACTGTCCTGCCGTCGACTTCTCTATATCCTCCTCGTCTATGCATGCGCCAGTA\
              AGAATCTATTCTACCCAACACATAACCAATAGAGTTCAGTCAATCTAAGTCGATCAGTTT\
              AGAGGTCGGATTATTCTAGCCGTGAAGTGCAAAGCACGGTCTCCCACCCAATGTATGCAT\
              TCGACGCGCGCGCGGTCACATGTAATTGCTCGGCACGAGCAACTGGGATACTAACACTTC\
              AGCGTCGTAATGTGCTAACGCATGATGACATTTTAAGAAATAGGACGCACCTCTCTCTCA\
              GAAGGCGTGCTGTTACCAGAGGGGTCACACTGGCAGCTCTACAACATTGGCGGCATGAAC\
              AGTGCGTGCCAGAGTGCACGGCACTTATGTCTTAGGATCTCCCGGGGGATCTTGTTAGCC\
              GTTCCATTGTCAAGCTTGAGAAAGATCCTTTGGAGTACCTGTTCACCGCTGTCTTATCGC\
              TTGGCCCCAAATTGACACCTCGGTTACGGTGAGAAATCGTGCCGGAGGCACTATAAGCTT\
              CCGT\
              ")
dna10_5 = Seq("CTGACGGGATCAGCTAGGGCGAGAATATTGCGAGCAGTTAAGTGCCTAGGACGTAGAATG\
              CCGCGAGAACAGTGGTTATGAGCAATAAGACGCACGGGGTGCAGGACTACAAGCCCCCCA\
              TACGACGTTCCCCGCAGTTCTAGCGAGGTAACCACATACGACCTAACTAGAGGCTTGCCA\
              GGGTGTTAGATTGGTCTACCACCCACCCTAGTTCCCGTAAAAAAGTTTTAGCGACTTGCT\
              GTTCGCGCTTCACCCGATGCATTCGCTGTCCATTGTCATTAAATCTGCTACACATTTCTA\
              TTGCTATTACTGGGTACAACCCCGCTGCGGACTTATTATGTTAAGTGATGTCCCTGCTAA\
              TCACAGCAAACGCGACTGTGTTTAGCTGTTATAATTGAATACAATAACAAGGGTTCTGTC\
              TATTTGGTGCCCCACTCCTAATATGTAGTCGCGCACGCGTCCTATATTTGATCTGCGCCT\
              ACATCTGCATGCACTTTCATCATTACAGCTATGCCCAATCTTGGTAGTAGTAGCTTTTCC\
              TAACCCTGCATCTCCGACAGGTACGTCGTTATGTGCCGATGACGCTCTTCTAAGGCCTCG\
              CACCCTGGTGTAAGGCACCTCACCACCTTTACTGAGCACTTTGCCTGGGCCCGGACTACA\
              GCAAGTCGACAACCGTAGCCAGATGACGAAAAGCCGCGGCGTGCCTTTGTAGGCATGAGT\
              TGGGTCTAGAAGCAGGAATGTATTATGTGAACCTGCAACTCCAACAACTGGCCAGGCAAT\
              CGCGATAGCAGGCCTCAGTAGTACACCCTGCGTGCTGGCATATCAAACAGAAACGCCATG\
              GACGGCGTCCTGACGCTTTATTCTTCCAGGTGGCTCGGTTATAGACATTTGGTTTACCTC\
              TATGTGAGACAAGTCCTGATGCAGGACATGTGGCATAATTGCCGTACTGCACGAGGAACG\
              ACCT")
dna10_6 = Seq("TGTAGTCGTGGCAATGGGTGAAGGGCAGCAATAGCTCATTACATAATTCATCGGCGGATT\
              TCTTTTGGTTAGATCATCATGTGATAACCATATATTGGGCGACGTCAAGAATGCAATGCA\
              GATGGCCAGTTTATCTATCCAACTAAATGCACCGCAGTGTAATGGGTTGTGCATTGGCGC\
              CTACAGATACACTTTAAATCTCCTCTGCATATATTCAACGTTAACCTACGGTGTATTCGG\
              AACGATGCTAAGGCATTGCGGTTTTGCCTGCCATTAAACCGAAGAAACAGACCTCATTAG\
              ACTCTGAACTGCTTGGCTTACAAACTGAAATTGAAGGCTTGTGACGCCAGCCGGCCACCA\
              GGGTGTGGGTGATAGGTATATAAAGATCTCAACAGGGCAATAGTAAATCAACTTCGAATA\
              CATACGTCGATTGGCGGTGATCAAGGCGCTAGTGTTGCAGCCCATGCATATCTCTTAAGT\
              TTACTGTTATTGGTCCGACTTGCCAGGGTGTAGGAAGTTCCGACACCGCCAAAACTTTTA\
              GGGCACCGGGCAGAAGAGTTCCAGTCTCGGCCTAACAGTTCGTGTGCAACGTCGTTGTAA\
              CCATGTGGGGAGTTCCCGTATCCCGGCGAAGACTTAATACGATGTCTTGACTATCGCGCA\
              CCTAAGTCTCCCAATTCCTTGTATCGGTACGACGCGATCGTCTTCTAAGACGGGCACGGG\
              CAATTGGTCTCATCACGAGCGAGGCCTGGGAGAGATTATCCAGGGACCCACGCTCTTGCA\
              AACGAAGTAACAAGTGCTGACCTGATTGTCTCTCTATCGCATCAATCGCACTCCAAACAC\
              TGCTCAGGCCGGTAGCTGTACGAAAGTGAGGGTTTTTAGTTATGGACGCATATCCGACAG\
              AACAGCGTACTTGAAATTCAACTCACTTCAGCTGATCTGGCTATAGATTCACATGCCCTC\
              GATC")
dna10_7 = Seq("GTACAGACCAACAGTAGACAGGTAAGGACCGTCAATACTGCTTCATAGTCTGATCGCCGG\
              TAGGTGTTGCGTATGCTTAAGTTCCAAATAGTTTAGCCGTTCTCCATGAGCACTACTTCA\
              GCCTTCACACTGGGCGCGAAAGTTTCACTTGCCAACAAGCGACATATCTGTGAAATGTTG\
              GCGCCTTGTACCGAGCTCACCAAACTCCTCTTAACGGCCGGACGAATTTCGGATGGGGTC\
              CGCCCGACTGAAATGAAAGCTCCCGCCTTTGTCCAGTCTAGTAACTTAAATTATCTTACC\
              TGATAAAAAGCTTTCAGCGTCATGCAATTCGACGTAGTATAGACCAACTCCCATCGTCAT\
              CTATAGGCCAAGAGTTTTATTGTAACAGAAGTGCTGGTCACTCACTTAACGTATCCGTTA\
              CTCCACACACTTTATGCGGAGGGGCATGGAGTTTAACATAACACATGTTACGCTACCAAG\
              CTATTGGTCTCCGTTTATCGTTTGCACCCAGCATACTAGACTACTTCCCACGATACCAGT\
              GGATTCCGACAGCCTTTGGGTCCCTCGGGGATTAACGCGGGTGGATCGGATGCCACGGCC\
              CTCTTTTTCGCGGAGTTTATGGATGTCGGCGAAGTCGGCGTTATGTGGCGTAGTATCGGC\
              CTACGACAAAAAAGTTCTAGACGTGCGCAAGACGACTTACCCCAGGCCCTTCATTAGCAG\
              GTTTCTCGCGGAGCCCGAATATGGGTCTGCAGTGAGGCGTCCGAAATTTAGAAATTAACG\
              GACATTCATAAGTTGTCATGAGTCGCCGGCCACCCAGAGAAGTTACAACGCCTCGGGGCT\
              TTGCTGTACAGTGATCATGGATATCTCATTATTACGACAGATAGGATGCCGCACTCCTGA\
              GGCCTCCCATTTGCTGCAAAAGGTCTGAGCTCAAGAGTCAATATAGCTCGCACGTCTCTA\
              TCTC")
dna10_8 = Seq("TCAGTAGCTACTACGCCAATCGACGGGTCGGACCTAACACGTCTCACGATCTTACTCACG\
              TCCCGGAGAAGCATTCTAGTAGCTTCTGATCGTCTAACAATACGTGATACCGTCTGAGCT\
              CAATTTGAGTGACTAGAGTCCTCAGAGGTACGTTGCTCAGCTTGGATTATGGTCCTTTCA\
              CGGTCTCCCGGACCGGCCCCTATAGATAGTCGCGGACGTTGAAAACACACAAGAATCGAC\
              GCAGATCACATAGCGGTGCCTATTCAAAGTAGATATCTTTCTATGGAGATTTATAGGTAG\
              CTGTGAAATTGAGTCATGCCCAGCTTCATCTCAGAGGGCATAGGGGAGCGCTGAAGGTGG\
              TGACTCAGCCTCCTAATGGCATAGAAGACCGTAAACGACCACAACCTTTCTTCAGATGTG\
              GTGATCAGAGCGCATTCGTTATACAGGTCTCGACCTCTTTACTTAGACGAAAAGCTTGAA\
              CGCATTGTAGATGCCTGCATCAGAAGAACATCCCAGCACACAGCAGTCCTGCTTCAGGGG\
              GGTCTTTTGTCGGCAGCCGATCGTTCCTTTAGATATGGTGACTCGGGTCAGAATCCTATT\
              GAACGAGTCCTTCTCTCTCATCATTCCAGCAAGCCCCCGAGACGGCTATTCTTTGTGTAT\
              TGGCGCAGAAGGCGGCACGTTTAAGCTCATATAGAAGTACTTTTCTTATGAGTGCCCAAT\
              TCGTCACTGGGCCCTACGGACCATGAAGGGGACAGTCGTTGTGCTGTTCCTTAGATAGAT\
              GAGCAAGACGCACCGATCTAGTGGCCTGAAACTGGAACATGATGCCACACAGTCTTATAT\
              TGAGCTGGGCAAATCGGGCCGTCGATACCCCGAGATGCAACAGGGCGTGGTGTGAAAAGT\
              GACGGCCCGCTATCCTGTGAAAGTTGCCCCGGCTACTCCATTTCCGGCCAGTGCGTTACG\
              TCGT")
dna10_9 = Seq("AATCCGATTCCTGGTGCTTCATTTCTATTCCCGGGGCTTTTCATTTGGTTCAGCCATAAG\
              GCAGAGGGTCCAGTGTCACTTAGTAGAGGCGTAACCAGATCAGTGAGATTTCGTTACGTG\
              CTATCTAGGCTAGGCAAAATATATGGTCCCCGCCTTGGAAGTATTGCATGCCGAATGTAC\
              GTATTTTTGGCGCAGTACCTCCGCTAGTAAAACGCCTATCGTTGCGGCTAATAGACATTT\
              GTTACAACAACGGTTGACTGCTGAAGCCCCCTGCAAGAGGCATAAGCAGACGCATGTATC\
              TTTCCACTTACCGTACTCTCTGCCACACCTACCTATCCGTTTCGTACAAGATTAGCTAAA\
              TTTATCCAGCGAGTCAACCGTCGGTGGCGGCTGAAGATTCAAAACGGCACCGTGCACGGG\
              GGCTTGGTGATGTGGTCCGGACGGAAGCATTCTTGTGATATTACCTCCGCCACCACATGT\
              ACTTAGATGTCAGCCGGGTCGAAGCTCGACTCACTGTCGCAAATTAAAAGGCCCTCGACC\
              TCGATCGCAAAACCTTCGAACAGATTGGTCTACGTGACATAGGTGACCTCATAGTTCGGG\
              AAAACGCCCCTTAGAGAGTCATTCGGGAGATGCTGTTAGCGGATAACTCAATACGGTCGG\
              CTGACTGCACGATTAGCGAATTGCTGTCTGCGCGGGCCTTTGTGATGCGATCAAAGGGCG\
              TCAACTAACGTTCGATAACCTCGGCACATCTTCACAGAGGCGTCCCGTGTATGTCAGACC\
              GCGTCAGCCGGCCTATAAAAGGCGTAGGGCGGTGTAGGACCGCGACCTAGGTTGAAGTTA\
              TGGCTGACCAACTCACCGTCGTTGGTGGCTTATCACTTAGACAAGAAAGACGATTATAGT\
              AGGAGTTCAGACCCTGGTTGTCCACTACGAGTTAGATAAACGCGGGTAGAAGTGCCTGGA\
              GGGC")
dna10_10 = Seq("TCGGCGTCCCACTCACTAGGTGGAATGTGTTTGCCGTTAGGTGATGGAACGCCTACTCTC\
               ACTCTCGTTTCGCGCAGTAATATCGACAATGGCGTCTGTCGGGCCCTCGTCACTCTGGTT\
               ACAATTATCAGGTAAAGGTCCGTCTCCCCAGAGTACACGATAACGATTGTTAACTCCATA\
               TCCTATGTGGGAATCGTTTTGGCCCATGTAATCTCCCTCCCCGTTTCACCCGTCATGAGC\
               AGAGGAGCGTCAACGAGAAGTGGGAATTCGAATTCCAGAAAGAGACTTTAGCCGGCAATG\
               AAGGGGTCATAGAGTGAACTAACGAAGGGTACTAGAGCAAAGGCCCTTCATACCCCTGGA\
               TAGCAGGATCTGGGCCATAACAGCATACCCTGTTTAACCTTGCTGAAGGTCACGTCGGGC\
               CTGGTAAATCAAGTCACATTCTATTCGCAGGAGTAACCATTGCCTTTGGCCTGTACCGAT\
               TTTAACACACAATTGCATCGACAGTACTCGGAGGACTCCCTGCAAGCAGCAGCACGGGTT\
               CGCCCCACTGAAGTGTGTGTTGAGTACCGCCGTACATGATAAGATGGGGCAGCCTGTGCT\
               CATAACCTGCGGATATTTCTCGAAGGACTGGAAGGAAGGCGCATTCCCTCCGATAGATCC\
               AACGAATCTGGCGTACTAGTAGGAGGAGATGGTCGATTCTCTCACGAACTTCCCTCCCGA\
               TGGAGTAACCATCCATGCGGCCCGAGAGCGTCGCAGGATGTGTCATGGGACCGCGGGCAC\
               AGGAATGCCCGTCCTAAGATCATATGGCCACGAACCAGACACATACCGTCATTTACTTCT\
               CAGGCCCTGATATCAGCGGACGATGACCCCGCGCATGGTGGGGGCAACACAAGGAGATGC\
               CTACATTGCAGTCTATTGCGATCATAGTGTTGAGAGGAGATGGCCTAAGGTCCGAATTCT\
               AACA\
               ")

sequences = [dna10_1, dna10_2, dna10_3, dna10_4, dna10_5, dna10_6, dna10_7, dna10_8, dna10_9, dna10_10]

with open('rosalind_cons.txt') as f:
    sequences1 = list(f)

length = len(sequences1)
pos = 0

aRow = [0] * length
cRow = [0] * length
gRow = [0] * length
tRow = [0] * length


while (pos < length):
    for sequence in sequences:
        base = sequence[pos]
        if (base == "A"):
            aRow[pos] = aRow[pos] + 1
        elif (base =="C"):
            cRow[pos] = cRow[pos] + 1
        elif (base =="G"):
            gRow[pos] = gRow[pos] + 1
        elif (base =="T"):
            tRow[pos] = tRow[pos] + 1
        else:
            print("error1")
    pos = pos + 1

consensus = Seq("")
aCount = 0
cCount = 0
gCount = 0
tCount = 0
maxCount = 0

pos = 0

while (pos < length):
    aCount = aRow[pos]
    cCount = cRow[pos]
    gCount = gRow[pos]
    tCount = tRow[pos]
    maxCount = max([aCount,cCount,gCount,tCount])
    
    if (maxCount == aCount):
        consensus = consensus + "A"
    elif (maxCount == cCount):
        consensus = consensus + "C"
    elif (maxCount == gCount):
        consensus = consensus + "G"
    elif (maxCount == tCount):
        consensus = consensus + "T"
    else:
        print("error2")
    
    pos = pos + 1
    
print (consensus)
print("A: " + ' '.join(map(str,aRow)))
print("C: " +' '.join(map(str,cRow)))
print("G: " +' '.join(map(str,gRow)))
print("T: " +' '.join(map(str,tRow)))
