import numpy as np
import pandas as pd
import Bio
from Bio.Seq import Seq
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet import generic_dna
from Bio.SeqUtils import GC


#Given two strings s and t, t is a substring of s if t is contained as a contiguous collection of symbols in s (as a result, t must be no longer than s).

s = Seq("TGAGAAGTAGGAGCAAGCAGCTTGCAAGCAGCCCCAAGCAGGACAAGCAGCAAGCAGCCAAGCAGGACAAGCAGTAAGCTCAAGCAGGGCAAGCAGACAAGCAGGAGAAGACAAGCAGCCATGCACAAGCAGCAAGCAGACCTGCAAGCAGCAAGCAGCTCAAGCAGTTAATCAAGCAGCAAGCAGCAAGCAGATCAAGCAGTCACAGATCGGACAAGCAGTTTGCAAGCAGCAAGCAGACAAGCAGCCTCAAGCAGCAAGCAGCTTCAAGCAGTGTACAAGCAGTTACCAAGCAGATCCATATCAAGCAGGGCACAAGCAGACCCAGAGTCAAGCAGGAATCAAGCAGCCAAGCAGCAAGCAGCAAGCAGTACAAGCAGCAAGCAGCAAGCAGCCAAGCAGTTCCAAGCAGCAAGCAGGGTAAGTGTCAAGCAGCAAGCAGGGTGCAGCAAGCAGTGCAAGCAGCAAGCAGCCCAAGCAGCAAGCAGCCAAGCAGCTCCCAAGCAGCCAAGCAGCAACAAGCAGAAGATCAAGCAGTGCCGCAAGCAGCATCCTTCAAGCAGACCAAGCAGCTCCACAAGCAGTATAGGGGGGGAGGCAAGCAGAAGGTCAAGCAGTCAAGCAGCGCACCCAAGCAGAAGCAAGCAGACAAGCAGCAAGCAGACAAGCAGTCAAGCAGACCAAGCAGAGCAAGCAGCCAAGCAGTCCCCAAGCAGACAAGCAGAGTCCCGTTCCAAGCAGGAAACAAGCAGCAAGCAGCAAGCAGTAAAGTCCCACAAGCAGGTTCCAAGCAGCAAGCAGCAACAAGCAGTGGCAAGCAGACAAGCAGTTCCAAGCAGCAAGCAG")
t = Seq("CAAGCAGCA")

locations = []
count = 0
loc = 0

while (count < len(s)):
    loc = s.find(t, start=count)
    if (loc > 0):
        count = loc + 1
        # adding plus 1 since the result needs to be in count from 1 format
        locations.append(loc + 1)
    else:
        count = count + 1

print(' '.join(map(str, locations)))
